### ISSUE TITLE
Blank page on npm run build

### ISSUE THREAD

**Issue by Mausino** [neuronetio/vue-gantt-schedule-timeline-calendar#1]
When you usin CLI to  in development .. there is no problem

The issue come if you decompile your deployment version.
You see the blank index page.

The issue is that in index.html is missing the dot before slasch
<link rel=icon href=/favicon.ico> -> <link rel=icon href=./favicon.ico>

When dot is added to all pathes.. the deployment version is working.

**Comment by neuronetio** [comment]
this is the standard vue cli project
maybe you need dot if you are opening it from hard drive?
