### ISSUE TITLE
Documentation for Including Plugins

### ISSUE THREAD

**Issue by SYPODan** [neuronetio/vue-gantt-schedule-timeline-calendar#2]
I'm trying to make use of the ItemMovement plugin included with GSTC. In the code examples on the regular version it just includes the plugin JS file from the "dist" directory, but there doesn't seem to be any similar examples showing how to include the plugins from within this Vue version. 

I've tried including the plugin JS directly from the GSTC package, but it still gives a "ItemMovement is not defined" error.

Would we be able to get some guidance for this?

**Comment by neuronetio** [comment]
Ok, I will add some documentation soon (maybe today)

**Comment by SYPODan** [comment]
> Ok, I will add some documentation soon (maybe today)

Thanks!

**Comment by neuronetio** [comment]
https://github.com/neuronetio/gantt-schedule-timeline-calendar#plugins
